version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASENAME=${DB_DATABASENAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASENAME}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

